### ISSUE TITLE
No Such Property Error

### ISSUE THREAD

**Issue by ianwalter** [geofflane/grails-constraints#5]
I installed the plugin. I ran the create-constraint script and created my constraint. I set the constraint on each property in my domain class. Then I tried to use the constraint in my 'create' template with the following line:

<% if(!cp?.secondary) { %>

And I get the following error when trying to generate views:

Error executing script GenerateViews: No such property: secondary for class: org.codehaus.groovy.grails.validation.ConstrainedProperty
No such property: secondary for class: org.codehaus.groovy.grails.validation.ConstrainedProperty

I'm really not sure why it doesn't recognize the constraint. I'm not trying to do anything overly complicated.

**Comment by geofflane** [comment]
The plugin is only loaded during runtime. The create scripts are run just with the command line, so the plugins like the Constraints plugin are not loaded, because they're not loaded, your custom constraints are not available at that point...

Long answer for, I don't think you can do what you're trying to do.
If I misunderstood, maybe create a little example app and send it to me so I can recreate the behavior and try and fix it.
